alias ll='ls -la'
alias nrs='sudo nixos-rebuild --use-remote-sudo switch'
alias nrb='sudo nixos-rebuild --use-remote-sudo boot'
alias ngc='sudo nix-collect-garbage --delete-older-than 14d'
alias code='codium'
alias rgf='rg --files | rg'